apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-audit
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy # audit configuration 
        metadata:
          name: policy-audit-example
        spec:
          severity: medium
          namespaceSelector:
            include: ["*"]
            exclude: ["kube-*", "openshift-*"]
          remediationAction: inform # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  annotations:
                    include.release.openshift.io/ibm-cloud-managed: "true"
                    include.release.openshift.io/self-managed-high-availability: "true"
                    include.release.openshift.io/single-node-developer: "true"
                    oauth-apiserver.openshift.io/secure-token-storage: "true"
                    release.openshift.io/create-only: "true"
                  name: cluster
                  ownerReferences:
                  - apiVersion: config.openshift.io/v1
                    kind: ClusterVersion
                    name: version
                spec:
                  audit:
                    profile: AllRequestBodies
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-audit
placementRef:
  name: placement-policy-audit
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-audit
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-audit
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: env, operator: In, values: ["dev"]}
